### ISSUE TITLE
Just a comment

### ISSUE THREAD

**Issue by danzimm** [jndok/harpoon#1]
I'm unsure how to contact you other than this so I'll put all my thoughts here:
1. Cool utility, at least in concept (see below). I love projects like this :smile: 
2. I strongly discourage the use of this in a real life application - while it seems sound for now, if the ABI changes at all this can have some pretty bad consequences. While I realize it's a 'hack', it really is hacky. In a real life situation I'd suggest using interposing (comex has a neat library on his github for this) or something like a static binary patch if really necessary. Both these things take away the issues you're having with hooking "return only functions", I believe, as well as include x64 support pretty simply.
3. To complete your hacky hack I suggest recalling 'vm_protect' to re protect those memory regions.

Overall nice repo :smile: 

Dan

**Comment by jndok** [comment]
Hey! Thanks for the comment. I really appreciate it! You are absolutely right, and this is indeed not intended to be used in any serious project (I plan to add and change many things, so maybe in future it will become usable). This is for now simply a test of my Mach/assembly knowledge.

Also, I wanted to thank you for https://github.com/danzimm/mach_fun, as I am working on another Mach-related project and you helped me **a lot** with your work!

**Comment by danzimm** [comment]
@jndok No problem - let me know if you want to pick my brain. That repo is a culmination of many hours reading docs/code for mach (spanning over a couple years in fact).
